  alias: Doorbell_pressed_automation 
  trigger: 
  - platform: mqtt 
    topic: dev/test
    payload: 'Capture!' 
  action: 
    - service: automation.turn_off 
      entity_id: automation.doorbell_pressed_automation 
    - service: script.turn_on 
      entity_id: script.doorbell_pressed_script 
    - delay: "00:00:5" 
    - service: automation.turn_on 
      entity_id: automation.doorbell_pressed_automation
