
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
camera: 
 - platform: mqtt 
   topic: dev/camera 
# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: ***
    allowed_chat_ids:
      - ****
notify: 
 - name: Telegram 
   platform: telegram 
   api_key: ****
   chat_id: ****
automation:
  alias: Doorbell_pressed_automation 
  trigger: 
    platform: mqtt 
    topic: dev/test
    payload: 'Capture!' 
  action: 
    - service: automation.turn_off 
      entity_id: automation.doorbell_pressed_automation 
    - service: script.turn_on 
      entity_id: script.doorbell_pressed_script 
    - delay: "00:00:5" 
    - service: automation.turn_on 
      entity_id: automation.doorbell_pressed_automation  
script:
  dev_publish_on_script: 
   sequence: 
     - service: mqtt.publish 
       data: {"topic":"dev/test", "payload":"ON"}     
script:
  script.dev_publish_on_script: 
   friendly_name: 'Capture doorcam photo' 
   icon: mdi:camera 
sensor:
  - platform: mqtt 
    name: "dev_test" 
    state_topic: "dev/test"
sensor:
  - platform: template 
    sensors: 
    camera_capture_time: 
      value_template: '{{states.sensor.dev_test.last_updated.strftime("%A %H:%M:%S")}}' 
      friendly_name: 'Camera captured time'  
group:
  Doorcam_view: 
   view: yes 
   entities: 
     - group.Doorcam_group 
  Doorcam_group: 
   entities: 
     - sensor.dev_test 
     - script.dev_publish_on_script 
     - sensor.camera_capture_time 
     - camera.mqtt_camera 
# Text to speech
#tts:
#  - platform: google_translate

#import scripts
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
